name: Task Request
description: Create a request for code to be written or 
title: "[TASK]: "
labels: ["draft"]
body:
  - type: markdown
    attributes:
      value: |
        Please be thorough in your task descriptions and linked resources
  - type: markdown
    attributes:
      value: |
        [Resource Library (Not a thing yet)]()
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: "Briefly explain what this task will accomplish/why it's important"
      placeholder: "This task will do x and y. This is important for z to work."
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Implementation Steps
      description: "Explain the general overview of how to implement the task. What should be done and where"
      placeholder: |
        1. Do x and y in z file.
        2. Do j and k in h file.
        3. Make sure y includes p functionality.
        4. Insure your unit tests account for g.
    validations:
      required: false
  - type: textarea
    id: links
    attributes:
      label: Relevant Links
      description: "Link the relevant resources that would be needed from the code base, resource library, or internet"
      placeholder: |
        [Link 1](https://link1) - An example of this thing in the codebase.
        [Link 2](https://link2) - Documentation for x.
    validations:
      required: false
  - type: textarea
    id: extra-info
    attributes:
      label: Extra Info
      description: Put any extra information here and/or change out the names
      value: |
        If you have any questions while working on this issue, post in the Programming Channel on Discord, reply to this issue on GitHub, or ask Dylan, Alex, Colin, or Nick at one of our meetings.
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What priority do you believe this task will be?
      options:
        - Low
        - Medium
        - High
      validations:
        required: false
  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty
      description: What difficulty do you believe this task will be?
      options:
        - Easy
        - Medium
        - Hard
    validations:
      required: false
  - type: input
    id: time
    attributes:
      label: Time Estimate
      description: About how long do you think it would take to sit down and complete this?
      placeholder: x hours
    validations:
      required: false
